// <auto-generated />
using System;
using HelloJobPH.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloJobPH.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251108160801_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelloJobPH.Shared.Model.Applicant", b =>
                {
                    b.Property<int>("ApplicantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicantId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HumanResourcesId")
                        .HasColumnType("int");

                    b.Property<string>("Middlename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("ApplicantId");

                    b.HasIndex("HumanResourcesId");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("int");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateApply")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("int");

                    b.Property<int?>("HumanResourcesId")
                        .HasColumnType("int");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<int?>("JobPostingId")
                        .HasColumnType("int");

                    b.Property<byte>("MarkAsCompleted")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ResumeId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("HumanResourcesId");

                    b.HasIndex("JobPostingId");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("int");

                    b.Property<int?>("HumanResourcesId")
                        .HasColumnType("int");

                    b.Property<int?>("JobPostingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("HumanResourcesId");

                    b.HasIndex("JobPostingId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.EducationalAttainment", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationId"));

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("IsGraduated")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("YearEnded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("YearStarted")
                        .HasColumnType("datetime2");

                    b.HasKey("EducationId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("EducationalAttainment");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.Employer", b =>
                {
                    b.Property<int>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployerId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployerId");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.HumanResources", b =>
                {
                    b.Property<int>("HumanResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HumanResourceId"));

                    b.Property<int?>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("HumanResourceId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("HumanResource");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.Interview", b =>
                {
                    b.Property<int>("InterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewId"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("AssignTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HumanResourceId")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ScheduledTime")
                        .HasColumnType("time");

                    b.HasKey("InterviewId");

                    b.HasIndex("ApplicationId")
                        .IsUnique()
                        .HasFilter("[ApplicationId] IS NOT NULL");

                    b.HasIndex("HumanResourceId");

                    b.ToTable("Interview");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.InterviewHistory", b =>
                {
                    b.Property<int>("InterviewHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewHistoryId"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InterviewBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterviewHistoryId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("InterviewHistory");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.JobPosting", b =>
                {
                    b.Property<int>("JobPostingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobPostingId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("int");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("int");

                    b.Property<int?>("HumanResourceId")
                        .HasColumnType("int");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<int>("JobCategory")
                        .HasColumnType("int");

                    b.Property<string>("JobRequirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SalaryFrom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalaryTo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobPostingId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("HumanResourceId");

                    b.ToTable("JobPosting");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.PendingRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmationToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middlename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PendingRegistration");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.Resume", b =>
                {
                    b.Property<int>("ResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResumeId"));

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("ResumeFileData")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ResumeId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("Resume");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.UserAccount", b =>
                {
                    b.Property<int>("UserAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAccountId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserAccountId");

                    b.ToTable("UserAccount");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.WorkExperience", b =>
                {
                    b.Property<int>("WorkExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkExperienceId"));

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkExperienceId");

                    b.HasIndex("ApplicantId");

                    b.ToTable("WorkExperience");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.Applicant", b =>
                {
                    b.HasOne("HelloJobPH.Shared.Model.HumanResources", "HumanResources")
                        .WithMany("Applicants")
                        .HasForeignKey("HumanResourcesId");

                    b.HasOne("HelloJobPH.Shared.Model.UserAccount", "UserAccount")
                        .WithOne("Applicant")
                        .HasForeignKey("HelloJobPH.Shared.Model.Applicant", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HumanResources");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.Application", b =>
                {
                    b.HasOne("HelloJobPH.Shared.Model.Applicant", "Applicant")
                        .WithMany("Appications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelloJobPH.Shared.Model.Employer", "Employer")
                        .WithMany("Applications")
                        .HasForeignKey("EmployerId");

                    b.HasOne("HelloJobPH.Shared.Model.HumanResources", "HumanResources")
                        .WithMany("Applications")
                        .HasForeignKey("HumanResourcesId");

                    b.HasOne("HelloJobPH.Shared.Model.JobPosting", "JobPosting")
                        .WithMany("Application")
                        .HasForeignKey("JobPostingId");

                    b.Navigation("Applicant");

                    b.Navigation("Employer");

                    b.Navigation("HumanResources");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.AuditLog", b =>
                {
                    b.HasOne("HelloJobPH.Shared.Model.Applicant", "Applicant")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ApplicantId");

                    b.HasOne("HelloJobPH.Shared.Model.Application", "Application")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelloJobPH.Shared.Model.Employer", "Employer")
                        .WithMany("AuditLogs")
                        .HasForeignKey("EmployerId");

                    b.HasOne("HelloJobPH.Shared.Model.HumanResources", "HumanResources")
                        .WithMany("AuditLogs")
                        .HasForeignKey("HumanResourcesId");

                    b.HasOne("HelloJobPH.Shared.Model.JobPosting", "JobPosting")
                        .WithMany("AuditLogs")
                        .HasForeignKey("JobPostingId");

                    b.Navigation("Applicant");

                    b.Navigation("Application");

                    b.Navigation("Employer");

                    b.Navigation("HumanResources");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.EducationalAttainment", b =>
                {
                    b.HasOne("HelloJobPH.Shared.Model.Applicant", "Applicant")
                        .WithMany("EducationalAttainments")
                        .HasForeignKey("ApplicantId");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.Employer", b =>
                {
                    b.HasOne("HelloJobPH.Shared.Model.UserAccount", "UserAccount")
                        .WithOne("Employer")
                        .HasForeignKey("HelloJobPH.Shared.Model.Employer", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.HumanResources", b =>
                {
                    b.HasOne("HelloJobPH.Shared.Model.Employer", "Employer")
                        .WithMany("HumanResources")
                        .HasForeignKey("EmployerId");

                    b.HasOne("HelloJobPH.Shared.Model.UserAccount", "UserAccount")
                        .WithOne("HumanResource")
                        .HasForeignKey("HelloJobPH.Shared.Model.HumanResources", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.Interview", b =>
                {
                    b.HasOne("HelloJobPH.Shared.Model.Application", "Application")
                        .WithOne("Interview")
                        .HasForeignKey("HelloJobPH.Shared.Model.Interview", "ApplicationId");

                    b.HasOne("HelloJobPH.Shared.Model.HumanResources", "HumanResource")
                        .WithMany("Interviews")
                        .HasForeignKey("HumanResourceId");

                    b.Navigation("Application");

                    b.Navigation("HumanResource");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.InterviewHistory", b =>
                {
                    b.HasOne("HelloJobPH.Shared.Model.Application", "Application")
                        .WithMany("InterviewHistorys")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.JobPosting", b =>
                {
                    b.HasOne("HelloJobPH.Shared.Model.Employer", "Employer")
                        .WithMany("JobPost")
                        .HasForeignKey("EmployerId");

                    b.HasOne("HelloJobPH.Shared.Model.HumanResources", "HumanResource")
                        .WithMany("JobPostings")
                        .HasForeignKey("HumanResourceId");

                    b.Navigation("Employer");

                    b.Navigation("HumanResource");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.Resume", b =>
                {
                    b.HasOne("HelloJobPH.Shared.Model.Applicant", "Applicant")
                        .WithMany("Resume")
                        .HasForeignKey("ApplicantId");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.WorkExperience", b =>
                {
                    b.HasOne("HelloJobPH.Shared.Model.Applicant", "Applicant")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("ApplicantId");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.Applicant", b =>
                {
                    b.Navigation("Appications");

                    b.Navigation("AuditLogs");

                    b.Navigation("EducationalAttainments");

                    b.Navigation("Resume");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.Application", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Interview");

                    b.Navigation("InterviewHistorys");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.Employer", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("AuditLogs");

                    b.Navigation("HumanResources");

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.HumanResources", b =>
                {
                    b.Navigation("Applicants");

                    b.Navigation("Applications");

                    b.Navigation("AuditLogs");

                    b.Navigation("Interviews");

                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.JobPosting", b =>
                {
                    b.Navigation("Application");

                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("HelloJobPH.Shared.Model.UserAccount", b =>
                {
                    b.Navigation("Applicant");

                    b.Navigation("Employer");

                    b.Navigation("HumanResource");
                });
#pragma warning restore 612, 618
        }
    }
}
